DELETE http://localhost:3001/api/persons/63e102cc2fdee29a00f96c48

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "://fullstackopen.com/en/part4/structure_of_backend_application_introduction_to_testing",
    "number": "123-1234566"
}

###
PUT http://localhost:3001/api/persons/63e0ca04cbdaa809adda2b05
Content-Type: application/json

{
    "name": "ok ok ok 000 test frank",
    "number": "123-1234566"
}

###
GET http://localhost:3001/api/persons/63e102cc2fdee29a00f96c48